set( _STB_HEADER_SEARCH_DIRS "${MYPROJECT_DIR}/3rdParty/stb")


# Search for the header
FIND_PATH(STB_INCLUDE_DIR "stb_include.h" PATHS ${_STB_HEADER_SEARCH_DIRS} )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(STB DEFAULT_MSG STB_INCLUDE_DIR)